/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import eu.nisoft.gradle.docker.StartContainerTask
import org.gradle.api.internal.project.ProjectInternal
import org.gradle.kotlin.dsl.register
import org.gradle.testfixtures.ProjectBuilder
import org.junit.jupiter.api.assertDoesNotThrow
import kotlin.test.Test

class GradleDockerPluginPluginTest {
    @Test fun `plugin can be applied`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        assertDoesNotThrow {
            project.plugins.apply("eu.nisoft.docker")
        }
    }
}
